package charles.nocompany.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import charles.nocompany.greendao.TestTable;
import charles.nocompany.greendao.Teacher;
import charles.nocompany.greendao.Student;

import charles.nocompany.greendao.TestTableDao;
import charles.nocompany.greendao.TeacherDao;
import charles.nocompany.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testTableDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final TestTableDao testTableDao;
    private final TeacherDao teacherDao;
    private final StudentDao studentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testTableDaoConfig = daoConfigMap.get(TestTableDao.class).clone();
        testTableDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        testTableDao = new TestTableDao(testTableDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(TestTable.class, testTableDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        testTableDaoConfig.getIdentityScope().clear();
        teacherDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
    }

    public TestTableDao getTestTableDao() {
        return testTableDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
